<?php

require_once __DIR__ . '/../../util/Constants.php';
use util\Constants;

?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
    <link rel="stylesheet" href="./View/css/base-styles.css">
    <link rel="stylesheet" href="./View/css/components.css">
    <link rel="stylesheet" href="./View/css/about-styles.css">
    <link rel="stylesheet" href="./View/css/dashboard-styles.css">
</head>
<body>

<nav class="nav">
    <div class="logo-section">
        <a class="logo-href" href=<?php echo Constants::PROJECT_URI; ?>>
            <h1>Event Organizer</h1>
        </a>
    </div>
    <div class="nav-buttons">
        <a href="event-list"><button>Events</button></a>
        <a href="search"><button>Search</button></a>
        <a href="myProfile"><button>My Profile</button></a>
        <a href="about"><button>About Us</button></a>
        <a href="logout"><button>Logout</button></a>
    </div>
</nav>

<main class="main">
    <section class="about-container">
        <h2>About Us</h2>

        <div class="profile-image">
            <img src="./View/pics/aboutUs.jpg" alt="About Us picture">
        </div>

        <section class="about-details">
            <h2>Who Are We?</h2>
            <p>We are passionate event organizers dedicated to making planning easier and more enjoyable. Our platform helps you manage, find, and organize events effortlessly.</p>

            <h2>Our Mission</h2>
            <p>We strive to simplify event management by providing user-friendly tools, seamless interactions, and a vibrant community of organizers and attendees.</p>
        </section>
    </section>
</main>


</body>
</html>
