<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Event Organizer</title>
    <link rel="stylesheet" href="/View/css/mainPage-styles.css">
</head>
<body>
<header class="navbar">
    <div class="logo">
        <h1>Event Organizer</h1>
    </div>
    <nav>
        <ul class="nav-links">
            <li><a href="#about">About</a></li>
            <li><a href="#features">Features</a></li>
            <li><a href="#contact">Contact</a></li>
            <?php
            if(isset($_SESSION['logged'] ) && $_SESSION['logged']){
                echo "<li><a href='/logout' class='login-btn'>Logout</a></li>";
            } else {
                echo "<li><a href='/login' class='login-btn'>Login</a></li>";
            }
            ?>
        </ul>
    </nav>
</header>



<section id="login" class="login-form">
    <h2>Login</h2>
    <form action="/login" method="post">
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" name="password" placeholder="Password" required>
        <button type="submit">Login</button>
    </form>
    <?php
    if(isset($_SESSION['error'] ) && isset($_SESSION['errorMsg']) && $_SESSION['error']){
            echo "<p class='error'> " . $_SESSION['errorMsg'] .  "</p>";
        }
    ?>
    <p>Don't have an account? <a href="/sign-up">Sign up here</a>.</p>
</section>

<footer>
    <p>&copy; 2024 Event Organizer. All rights reserved.</p>
</footer>
</body>
</html>
