<?php
$username = $_SESSION['username'] ?? '';
$email = $_SESSION['email'] ?? '';
$firstName = $_SESSION['firstname'] ?? '';
$lastName = $_SESSION['lastname'] ?? '';
$birthdate = $_SESSION['birthdate'] ?? '';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="/View/css/dashboard-styles.css">
</head>
<body>
<nav class="dashboard-nav">
    <a class="logo-href" href="/">
        <h1>Event Organizer</h1>
    </a>
    <ul>
        <li><a href="#events">Manage Events</a></li>
        <li><a href="/edit">Edit Profile</a></li>
        <li><a href="/logout">Logout</a></li>
    </ul>
</nav>
<main class="dashboard-main">
    <h1>View Profile</h1>
    <div class="profile-info">
        <p><strong>Username:</strong> <?php echo htmlspecialchars($username); ?></p>
        <p><strong>First Name:</strong> <?php echo htmlspecialchars($firstName); ?></p>
        <p><strong>Last Name:</strong> <?php echo htmlspecialchars($lastName); ?></p>
        <p><strong>Birthdate:</strong> <?php echo htmlspecialchars($birthdate); ?></p>
        <p><strong>Email:</strong> <?php echo htmlspecialchars($email); ?></p>

    </div>
</main>
</body>
</html>
