<?php

require_once __DIR__ . '/../../util/Constants.php';
use util\Constants;

?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" href="./View/css/base-styles.css">
    <link rel="stylesheet" href="./View/css/components.css">
    <link rel="stylesheet" href="./View/css/signup-styles.css">
</head>
<body>
<div class="signup-container">
    <h1>Create Your Account</h1>
    <form action="create-acc" method="post">
        <input type="text" name="firstname" placeholder="First Name" required>
        <input type="text" name="lastname" placeholder="Last Name" required>
        <input type="date" name="birthdate" required>
        <input type="email" name="email" placeholder="Email" required>
        <input type="text" name="username" placeholder="Username" required>
        <input type="password" id="password" name="password" placeholder="Password" required>
        <input type="password" id="confirm-password" name="confirm-password" placeholder="Confirm Password" required>
        <button type="submit" class="btn-signup">Sign Up</button>
    </form>
    <a href=<?php echo Constants::PROJECT_URI; ?>>
        <button style="background-color: lightblue; border: none; padding: 8px 16px; cursor: pointer; margin-top: 20px">
            Return Home
        </button>
    </a>
</div>
</body>
</html>
